name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install zlib
      run: sudo apt install zlib1g
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 6.0.100-preview.2.21155.3
        
    - name: publish
      run:  dotnet publish -o ./publish/ --nologo -c release 
      
    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ./publish/wwwroot/index.html
        base_href: /ABlazorPong/
        
    - name: Add .nojekyll file
      run: touch ./publish//wwwroot/.nojekyll
        
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ./publish/wwwroot/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
